/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as EstudioRouteImport } from './routes/estudio'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as EpisodeEpisodeIdRouteImport } from './routes/episode.$episodeId'
import { Route as ShowShowIdRouteImport } from './routes/show.$showId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioRoute = EstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeEpisodeIdRoute = EpisodeEpisodeIdRouteImport.update({
  id: '/episode/$episodeId',
  path: '/episode/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowShowIdRoute = ShowShowIdRouteImport.update({
  id: '/show/$showId',
  path: '/show/$showId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/estudio': typeof EstudioRoute
  '/explorar': typeof ExplorarRoute
  '/instalar': typeof InstalarRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/estudio': typeof EstudioRoute
  '/explorar': typeof ExplorarRoute
  '/instalar': typeof InstalarRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/estudio': typeof EstudioRoute
  '/explorar': typeof ExplorarRoute
  '/instalar': typeof InstalarRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/estudio'
    | '/explorar'
    | '/instalar'
    | '/episode/$episodeId'
    | '/show/$showId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/estudio'
    | '/explorar'
    | '/instalar'
    | '/episode/$episodeId'
    | '/show/$showId'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/estudio'
    | '/explorar'
    | '/instalar'
    | '/episode/$episodeId'
    | '/show/$showId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  EstudioRoute: typeof EstudioRoute
  ExplorarRoute: typeof ExplorarRoute
  InstalarRoute: typeof InstalarRoute
  EpisodeEpisodeIdRoute: typeof EpisodeEpisodeIdRoute
  ShowShowIdRoute: typeof ShowShowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio': {
      id: '/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof EstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$episodeId': {
      id: '/episode/$episodeId'
      path: '/episode/$episodeId'
      fullPath: '/episode/$episodeId'
      preLoaderRoute: typeof EpisodeEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$showId': {
      id: '/show/$showId'
      path: '/show/$showId'
      fullPath: '/show/$showId'
      preLoaderRoute: typeof ShowShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  EstudioRoute: EstudioRoute,
  ExplorarRoute: ExplorarRoute,
  InstalarRoute: InstalarRoute,
  EpisodeEpisodeIdRoute: EpisodeEpisodeIdRoute,
  ShowShowIdRoute: ShowShowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
